baseURL: "/"
title: A Cyber Island Inhabited by a Cyber Survivor
paginate: 5
theme: PaperMod2Plus

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 🪓
  description: "Nijat's Cyber Island"
  keywords: [Web3, Cloud, Back-end]
  author: Nijat
  # author: ["Me", "You"] # multiple authors
  images: ["/cover/twitter-cover.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/ico/favicon.ico"
    favicon16x16: "/ico/favicon-16x16.png"
    favicon32x32: "/ico/favicon-32x32.png"
    apple_touch_icon: "/ico/apple-icon-60x60.png"
    safari_pinned_tab: "/ico/apple-icon-152x152.png"

  label:
    text: "NTMV"
    icon: /other/Axe_001.png
    iconHeight: 50

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: 🪓
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: axe
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "&#127965;&#65039; A Cyber Island Inhabited by a Cyber Survivor"
    Content: Welcome to my island, where I occasionally spill the cyber-tea on all things decentralized networks, distributed systems, and cybersecurity.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/nijatoes"
    - name: youtube
      url: "https://www.youtube.com/channel/UCjiHQiwnE2Bn0hCy8IMiw-Q"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/nijatoes/blogoes/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  customapis:
    tvapURL: "https://tvap.nijatoes.com/visitors"
    plausibleURL: "https://app.axshelf.com/app.js"
    statDomain: "nijatoes.com"
    statusPage: "https://status.nijatoes.com/status/live"

menu:
  main:
    - identifier: rp
      name: Content license
      url: /license/
      weight: 9
    - identifier: videos
      name: Videos
      url: /videos/
      weight: 9
    - identifier: github
      name: Github
      url: https://github.com/njts/blogoes/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 8


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

languages:
    en:
        languageName: "English"
        weight: 1
        title: NTMV
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - identifier: rp
                  name: Content license
                  url: /license/
                  weight: 4
                - identifier: videos
                  name: Videos
                  url: /videos/
                  weight: 3
                - identifier: github
                  name: Github
                  url: https://github.com/njts/blogoes/
                  weight: 5
                - identifier: contact
                  name: Contact
                  url: /contact/
                  weight: 1

    tr:
        contentDir: content/posts/tr
        languageName: Turkish
        weight: 2
        title: NTMV - TR
        homeInfoParams:
            Title: "&#127965;&#65039; Tek Kişilik Bir Siber Ada"
            Content: Adaya hoş geldiniz. Burada bazen merkeziyyetsiz teknolojiler ve siber güvenlik ile ilgili küçük yazılarımı paylaşıyorum.
        taxonomies:
          category: FAcategories
          tag: FAtags
          series: FAseries
        menu:
            main:
                - identifier: rp
                  name: İçerik lisansı
                  url: /license/
                  weight: 4
                - identifier: videos
                  name: Videolar
                  url: /videos/
                  weight: 3
                - identifier: github
                  name: Github
                  url: https://github.com/njts/blogoes/
                  weight: 5
                - identifier: contact
                  name: İletişim
                  url: /contact/
                  weight: 1

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true
